name: Build
on: [push]
jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: cd backend && chmod +x ./gradlew && ./gradlew build
