[build]
  base = "frontend/"
  command = "yarn install && yarn simpleBuild"
  publish = "dist/pwa"

[[redirects]]
  from = "/api/*"
  to = "http://capgemini-loadbalancer-1573441832.eu-central-1.elb.amazonaws.com:8081/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
