server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

graphql:
    servlet:
      mapping: /api/graphql
      enabled: true

graphiql:
    enabled: true
    mapping: /graphiql
    endpoint:
      graphql: /api/graphql
    cdn:
      enabled: true
      version: 0:12:0

emission:
    commute:
        walking: 0.0
        bike: 0.0
        ebike: 25.0
        car:
            normal: 143.0
            hybrid: 90.0
        bus:
            shortterm: 80.0
            longterm: 29.0
        train:
            shortterm: 55.0
            longterm: 29.0
        tram:
            shortterm: 55.0
            longterm: 29.0
        plain:
            country: 214.0
            global: 999.0
        escooter: 126.0
    grocery:
      cattle: 13.3
      pig: 3.3
      poultry: 3.5
      lamb: 39.0
      fish: 3.1
      rice: 4.1
      noodles: 0.9
      fries: 5.7
      butter: 23.8
      cream: 7.6
      milk: 0.9
      potatoes: 0.2
      lenses: 0.3
      oatmeal: 0.3




