name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew build
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          cd frontend
          npm install --global yarn
          yarn install
          yarn simpleBuild
